name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Build, test, Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn test
      - run: npm version patch

      - name: Publish on NPM
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
