name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn test

  update:
    name: Update Version
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Setup GIT"
        run: |
          git switch -c master
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Update & push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm version patch
        run:  git add package.json
        run: git commit -m "chore: release" --no-verify
        run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"

  publish:
    name: Publish
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish on NPM
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
