name: Release

on:
  pull_request:
    branches:
      - "release/**"

jobs:
  update:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.GP_TOKEN }}
